# Use root/example as user/password credentials
version: '3.1'

services:

  webapp:
    build: .
    image: code-generator:latest
    ports:
      - 80:80
      - 443:443
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_volumetest3:/data/db
    ports:
      - 27017:27017 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo_volumetest3: